# Use official lightweight Node image
FROM node:20.11-alpine

# Set working directory inside container
WORKDIR /app

# Copy package files first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app
COPY . .

# Expose port (match your app)
EXPOSE 3000

# Start app
CMD ["node", "server.js"]